LittleLemon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls'), name='home'),
]

restaurant/urls.py
from django.urls import path
from .views import *

app_name = 'restaurant'

urlpatterns = [
    path('home/', home_page, name='home-page'),
    path('menu/', MenuList.as_view(), name='menu-list'),
    path('menu/<int:pk>/', MenuDetail.as_view(), name='menu-detail'),
    path('booking/', BookingCreateView.as_view(), name='booking'),
    path('successful-booking/', successful_booking, name='successful-booking'),
    path('booking-details/<int:pk>/', BookingDetail.as_view(), name='booking-detail'),
    path('booking-list/', BookingList.as_view(), name='booking-list'),

    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),


]

restaurant/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Booking(models.Model):

    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20, blank=True)
    guest_number = models.IntegerField()
    comment = models.CharField(max_length=1000, blank=True)
    last_modification_time = models.DateTimeField(auto_now=True)
    # purchases = models.ManyToManyField('Menu', related_name='purchases', blank=True)

    def __str__(self):
        return f'guest name:{self.first_name} {self.last_name} \n' + \
                f' guest number:{self.guest_number} -- last update time:{self.last_modification_time}'


class Menu(models.Model):
    name = models.CharField(max_length=20)
    price = models.IntegerField(null=True)
    menu_item_description = models.TextField(max_length=1000, default='', blank=True)

    def __str__(self):
        return f'{self.name}'

restaurant/forms.py
from django.contrib.auth.models import User

from .models import Booking
from django.forms import ModelForm, Form
from django.forms.widgets import Textarea


class BookingForm(ModelForm):

    class Meta:
        model = Booking
        fields = ['first_name', 'last_name', 'comment', 'guest_number']
        widgets = {
            'comment': Textarea()
        }

restaurant/views.py
from django.shortcuts import render
from .models import *
from django.views.generic import ListView, DetailView, CreateView

from .forms import BookingForm
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


def home_page(request):
    context = {'user': request.user}
    return render(request, 'restaurant/home-page.html', context)


def header(request):
    context = {'user': request.user}
    return render(request, 'header.html', context)


class CustomLoginView(LoginView):

    template_name = 'restaurant/login.html'
    next_page = reverse_lazy('restaurant:home-page')
    redirect_field_name = 'next'


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('restaurant:home-page')
    template_name = 'restaurant/logged_out.html'


class MenuList(ListView):
    model = Menu
    template_name = 'restaurant/menu.html'
    template_name_suffix = ''
    ListView.context_object_name = 'menu_items'


class MenuDetail(DetailView):
    model = Menu
    template_name = 'restaurant/menu-item-detail.html'
    context_object_name = 'menu'


class BookingCreateView(LoginRequiredMixin, CreateView):
    model = Booking
    template_name = 'restaurant/booking.html'
    form_class = BookingForm
    context_object_name = 'booking_form'
    success_url = reverse_lazy('restaurant:successful-booking')

    login_url = reverse_lazy('restaurant:login')
    redirect_field_name = 'next'


def successful_booking(request):

    return render(request, 'restaurant/successful-booking.html')


class BookingDetail(DetailView):
    model = Booking
    template_name = 'restaurant/booking-detail.html'
    context_object_name = 'booking'


class BookingList(ListView):
    model = Booking
    context_object_name = 'booking_list'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}
  	Little Lemon
  {% endblock %}</title>
</head>
<body>

{% block header %}
  {# Header #}
{% include 'header.html' %}
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
  {# Footer #}
{% include 'footer.html' %}
{% endblock %}

</body>
</html>

templates/footer.html
<hr>
<div>
{#  footer icon #}
</div>

<div>
{#  footer contents #}
  <div align="center">
    <p>
    All rights are reserved for Little Lemon corporation
    </p>
  </div>
</div>

templates/header.html
{% load static %}

<div align="center">
{# header image  #}
  <img src="{% static 'restaurant/littlelemon_header.png' %}" alt="little lemon header">
</div>

<div>
  <p> is anonymous : {{ user.is_anonymous }} is authenticated : {{ user.is_authenticated }}</p>
  {% if user.is_authenticated  %}
  	<span> User: {{ user.username }}</span><br>
    
    <form method="post" action="{% url 'restaurant:logout' %}" >
      {% csrf_token %}
      <input type="submit" value="Logout">
{#      <input type="hidden" name="next" value="next">#}
    </form>
  {% else %}
    <a href="{% url 'restaurant:login' %}"> Login </a>
  {% endif %}
</div>

<div align="center">
  <nav>
    <ul>
      <li><a href="{% url 'restaurant:home-page' %}"> Home </a></li>
      <li><a href="{% url 'restaurant:menu-list' %}"> Menu </a></li>
      <li><a href="{% url 'restaurant:booking' %}"> Book </a></li>
      <li><a href="{% url 'restaurant:booking-list' %}"> Booking list </a></li>
      
    </ul>
  </nav>
</div>

templates/restaurant/booking-detail.html
{% extends 'base.html' %}

{% block content %}
	<p>first name: {{ booking.first_name }}</p>
  <p>last name: {{ booking.last_name }}</p>
  <p>Guest Number: {{ booking.guest_number }}</p>
  <p>comment: {{ booking.comment }}</p>
  <p> Time: {{ booking.last_modification_time }}</p>
{% endblock %}

templates/restaurant/booking.html
{% extends 'base.html' %}

{% block title %}
	Booking
{% endblock %}

{% block content %}
	<div>
    please fill out the form 
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" >
    </form>
  </div>
{% endblock %}

templates/restaurant/booking_list.html
{% extends 'base.html' %}

{% block title %}
	Booking list 
{% endblock %}


{% block content %}
	{% for booking in booking_list %}
    <a href="{% url 'restaurant:booking-detail' pk=booking.pk %}"><p>
      {{ forloop.counter }}. first name: {{ booking.first_name }} , Last name: {{ booking.last_name }}
    </p></a>
	{% endfor %}
	
{% endblock %}

templates/restaurant/home-page.html
{% extends 'base.html' %}

{% block title %}
	home page
{% endblock %}

{% block content %}
  <div align="center">
    <h1> Home page of Little Lemon </h1>
  </div>
{% endblock %}

templates/restaurant/logged_out.html
{% extends 'base.html' %}

{% block title %}
	{{ title }}
{% endblock %}

{% block content %}
	You're Logged out successfully
{% endblock %}

templates/restaurant/login.html
{% extends 'base.html' %}

{% block title %}
	Login page
{% endblock %}

{% block header %}
  <h2> Login page  </h2>
{% endblock %}

{% block content %}
{#	login form #}
  <div align="center">
    
    {# next page logic when user redirected to login page  #}
    {% if next %}
    	{% if user.is_authenticated %}
    		<p> Your account doesn't have permission to access this page </p>
      {% else %}
        <p> please log in to visit the page </p>
    	{% endif %}
    {% endif %} 
  
    <form method="post" action="{% url 'restaurant:login' %}">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="login">
      <input type="hidden" name="next" value="{{ next }}">
    </form>
    
    <p>
      {{ next }}
    </p>
  </div>
{% endblock %}

templates/restaurant/menu-item-detail.html
{% extends 'base.html' %}

{% block title %}
	Menu Details
{% endblock %}

{% block content %}
	<div align="center">
    <h2> {{ menu.name }}</h2>
    <h4> {{ menu.price }}</h4>
    <p> {{ menu.menu_item_description }}</p>
  </div>
{% endblock %}

templates/restaurant/menu.html
{% extends 'base.html' %}

{% block title %}
  Menu 
{% endblock %}

{% block content %}
  <div align="center">
    {% for menu_item in menu_items %}
    	<p>
        <a href="{% url 'restaurant:menu-detail' pk=menu_item.pk %}">{{ menu_item.name }}</a>
        <span>
          {{ menu_item.price }}
        </span> <br>
      </p>
    {% endfor %}
  </div>
{% endblock %}

templates/restaurant/signup.html
{% extends 'base.html' %}

{% block title %}
	sign up page
{% endblock %}

{% block header %}
	
{% endblock %}

{% block content %}
	
{% endblock %}

templates/restaurant/successful-booking.html
{% extends 'base.html' %}

{% block title %}
	Booking Successful
{% endblock %}

{% block content %}
	<h3>
   your booking is saved successfully 
  </h3>
{% endblock %}